### ISSUE TITLE
Docker build job needs run

### ISSUE THREAD

**Issue by jdav-dev** [sedlund/acdcli#1]
acd_cli is out of date in the sedlund/acdcli image:
```
$ docker run --rm -it sedlund/acdcli version
acd_cli 0.3.1, api 0.8.7
```

I need the `--remove-source-files` argument added to `upload` in 0.3.2

**Comment by sedlund** [comment]
bumped to alpine 3.5 and triggered docker hub build

**Comment by jdav-dev** [comment]
Awesome, thanks
